### ISSUE TITLE
请教关于编译的问题

### ISSUE THREAD

**Issue by trytrytogo** [Huiaei/XDD-BUILD#1]
首先，感谢您的编译。

另外，由于设备限制，我只有ARM的设备，请请教一下后期有支持arm计划吗

**Comment by Huiaei** [comment]
可以自行fork仓库改action文件的编译部分，现在倒是在研究使用gox进行多版本编译

**Comment by Huiaei** [comment]
改完action了，现在编译出linux的amd64，arm64，arm三个版本了。

**Comment by trytrytogo** [comment]
> 可以自行fork仓库改action文件的编译部分，现在倒是在研究使用gox进行多版本编译

感谢回复。 我昨天看了一下，大概知道怎么弄了。 测试的时候go环境有问题，就放弃了。 

后面先把环境搞出来

**Comment by Huiaei** [comment]
> > 可以自行fork仓库改action文件的编译部分，现在倒是在研究使用gox进行多版本编译While the fork repository can change the Action File’s compilation section on its own, multiple versions of the action file are now being explored using GOX
> 
> 感谢回复。 我昨天看了一下，大概知道怎么弄了。 测试的时候go环境有问题，就放弃了。
> 
> Thanks for the reply. I took a look at it yesterday, and I think I know how to do it. The GO environment had a problem during testing, so I gave up.
> 
> 后面先把环境搞出来
> 
> Let’s get the environment out of the way

最好还是自己在实机上编译，我都不清楚我这个云编译的结果到底有没有用。
